<?php
ERROR_REPORTING(E_ALL);
INI_SET("DISPLAY_ERRORS", 1);
IF ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $CPF = $_POST['CPF'];
    $ENDERECO = $_POST['ENDERECO'];
    $TELEFONE = $_POST['TELEFONE'];
    $NOME = $_POST['NOME'];
    GRAVARUSUARIO($CPF, $NOME, $ENDERECO, $TELEFONE);
}
FUNCTION GRAVARUSUARIO($CPF, $NOME, $ENDERECO, $TELEFONE)
{
    $USUARIO = ARRAY(
    $CPF => ARRAY(
    'NOME' => $NOME,
    'TELEFONE' => $TELEFONE
    'ENDERECO' => $ENDERECO,
    ));
    $USUARIO_JSON = JSON_ENCODE($USUARIO);
    $NOMEARQUIVO = 'USUARIOS.TXT';
    FILE_PUT_CONTENTS($NOMEARQUIVO, $USUARIO_JSON, FILE_APPEND);
    ECHO "SUCEFULL!";
}
?>
<!DOCTYPE HTML>
<HTML LANG="EN">
<HEAD>
    <META CHARSET="UTF-8">
    <META HTTP-EQUIV="X-UA-COMPATIBLE" CONTENT="IE=EDGE">
    <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0">
<TITLE>ATV</TITLE>
<STYLE>
    BODY{
    BACKGROUND-COLOR: RGB(158, 441, 255);
    FONT-FAMILY: 'GILL SANS', CALIBRI, 'TREBUCHET MS', SANS-SERIF;
    ALIGN-ITEMS: ABSOLUTE;
    FONT-SIZE: LARGE;
    }
    INPUT{
    BORDER-RADIUS: 4PX;
    WIDTH: 40VH;
    HEIGHT: 4VH;
    CURSOR: POINTER;
    }
</STYLE>
</HEAD>
<BODY>
    <FORM METHOD="POST" ACTION="">
<LABEL FOR="NOME">NOME:</LABEL><BR>
    <INPUT TYPE="TEXT" NAME="NOME" ID="NOME"><BR><BR>
<LABEL FOR="CPF">CPF:</LABEL><BR>
    <INPUT TYPE="TEXT" NAME="CPF" ID="CPF"><BR><BR>
<LABEL FOR="ENDERECO">ENDEREÇO:</LABEL><BR>
    <INPUT TYPE="TEXT" NAME="ENDERECO" ID="ENDERECO"><BR><BR>
<LABEL FOR="TELEFONE">TELEFONE:</LABEL><BR>
    <INPUT TYPE="TEXT" NAME="TELEFONE" ID="TELEFONE"><BR><BR>
    <INPUT TYPE="SUBMIT" NAME="SALVAR" VALUE="SALVAR">
    </FORM>
</BODY>
</HTML>
